
replicaCount: 2

# informtion pour le service
image:
  repository: dahansop/jenkinsexam-movie
  tag: V26.0
  imagePullPolicy: IfNotPresent

secret:
  databaseUri: "postgresql://admin:password@movie-db:5432/moviedb"
  castServiceUrl: "http://cast-service:80001/api/v1/cast"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8002


# information pour la base de donn√©es
imagedb:
  repository: postgres
  tag: 12.1-alpine
  imagePullPolicy: IfNotPresent

persistencedb:
  existingClaim: ""
  enabled: true
  storageClassName: "local-path"
  accessMode: ReadWriteOnce
  size: 1Gi

secretdb:
  username: admin
  password: password

configmap:
  dbname: moviedb
  hostAuthMethod: trust

servicedb:
  type: ClusterIP
  port: 5432
  targetPort: 5432
